// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLU5IHEqdCOJk8GDJgPh2jr06_jW3VX4',
    appId: '1:832461030386:web:36531234eb2015751e616b',
    messagingSenderId: '832461030386',
    projectId: 'exemplo-sl',
    authDomain: 'exemplo-sl.firebaseapp.com',
    databaseURL: 'https://exemplo-sl-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo-sl.appspot.com',
    measurementId: 'G-DKBCQB03MH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxPQjU164h1ldl5kmdxylbdSZC7SV2rCQ',
    appId: '1:832461030386:android:8146872d74ae8b051e616b',
    messagingSenderId: '832461030386',
    projectId: 'exemplo-sl',
    databaseURL: 'https://exemplo-sl-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo-sl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVx--UUUMfSXY3fzLFMpNI92jfXsNUMJU',
    appId: '1:832461030386:ios:b1201248a2094b011e616b',
    messagingSenderId: '832461030386',
    projectId: 'exemplo-sl',
    databaseURL: 'https://exemplo-sl-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo-sl.appspot.com',
    iosClientId: '832461030386-cupg74iqqpvsg1vn3h3tdm13fjdj0a7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.httpSampleFire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVx--UUUMfSXY3fzLFMpNI92jfXsNUMJU',
    appId: '1:832461030386:ios:b1201248a2094b011e616b',
    messagingSenderId: '832461030386',
    projectId: 'exemplo-sl',
    databaseURL: 'https://exemplo-sl-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo-sl.appspot.com',
    iosClientId: '832461030386-cupg74iqqpvsg1vn3h3tdm13fjdj0a7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.httpSampleFire',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhLU5IHEqdCOJk8GDJgPh2jr06_jW3VX4',
    appId: '1:832461030386:web:899bc031dbef9c8f1e616b',
    messagingSenderId: '832461030386',
    projectId: 'exemplo-sl',
    authDomain: 'exemplo-sl.firebaseapp.com',
    databaseURL: 'https://exemplo-sl-default-rtdb.firebaseio.com',
    storageBucket: 'exemplo-sl.appspot.com',
    measurementId: 'G-9J0FCBMCLQ',
  );

}